# Generated by Django 5.1.1 on 2024-10-02 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('createdAt', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('EXECUTING', 'EXECUTING'), ('COMPLETED', 'COMPLETED')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_id', models.CharField(blank=True, choices=[('CS183D', 'CS183D')], max_length=200)),
                ('certificate_id', models.CharField(max_length=100, unique=True)),
                ('credentials', models.URLField(blank=True, max_length=300, null=True, unique=True)),
                ('is_created', models.BooleanField(default=False)),
                ('certificate_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.certificaterequest')),
            ],
        ),
        migrations.CreateModel(
            name='FailedCertificates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certificates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.certificate')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.certificaterequest')),
            ],
        ),
    ]
