# Generated by Django 5.1.1 on 2024-10-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_certificaterequest_report_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='roll_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
