# Generated by Django 5.1.1 on 2024-10-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_certificate_roll_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificaterequest',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
