# Generated by Django 5.1.1 on 2024-10-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_rename_createdat_certificaterequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='drive_link',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
